### ISSUE TITLE
projecten code

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#10]
Indien een project is aangemaakt met een juiste code bv. 2019 THHI XX1A 3001 en je wil nadien dit project bewerken bv. op actief zetten, dan moet de code opnieuw ingeven. SZAPP onthoudt de code blijkbaar niet.

**Comment by handihow** [comment]
Ik heb geprobeerd om dit probleem te reproduceren, maar het lukt me niet. Ik heb een nieuw project aangemaakt en kon daarna het project bewerken. De code was nog altijd aanwezig. Ik heb ook bestaande projecten bewerkt. Verder heb ik nog op de production site gekeken, ook daar kreeg ik de code weer in het bewerk scherm te zien.

**Comment by handihow** [comment]
Zou je met behulp van screenshots kunnen laten zien bij welk project het niet goed gaat?

**Comment by LucLens** [comment]
Kan het ook niet meer terugvinden. Zal aan het dagdromen geweest zijn ...
