### ISSUE TITLE
link toevoegen aan een evaluatiecriteria

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#11]
De link die je bij een evaluatiecriteria kunt plaatsen is super handig. Bv;. wanneer je een evaluatiecriteria niet geheel kunt vertalen, kun je verwijzen naar een filpmpje of naar een deel van je cursus of instructiekaart of ...

Is het mogelijk dat de link echter achter een ingegeven tekst komt te staan bv.
Volgende link: [https://drive.google.com/open?id=0B-g0woneg-wlUFdCTjVGbzJ6TkE]

wordt dan: [zie pagina 3 t/m 4](url) en door op deze tekst te klikken kom je op dezelfde webpagina uit als bovenstaande.

**Comment by handihow** [comment]
Dit is een goed idee. De link tekst is nu erbij geprogrammeerd. Je ziet dit nu op de staging website bij Leerplannen --> competenties. Hier kun je nu ook een link tekst ingeven. Als dit blanco wordt gelaten, dan krijg je de volledige link als tekst, en anders de tekst ingegeven bij de link tekst. 

Dit is te zien in de tabel onder leerplannen en ook projecten.

Als dit in de huidige vorm goed is dan kan ik dit ook doorzetten naar production.

**Comment by LucLens** [comment]
Dag Roeland

Ingave van tekst voor hyperlink is goed maar indien een leerling een
zelfevaluatie wil doen en hij naar deze link gaat moet hij op informatie
klikken en krijgt hij niet de tekst te zien (bv. zie pagina 4 voor meer
uitleg). Bedoeling is dat de leerling deze tekst ziet en hierop kan klikken
voor meer info.

Met vriendelijke groet,

Luc Lens
Coördinator vakgroepondersteuning techniek, ESF medewerker en coördinator
duaal leren.
Technisch Heilig-Hart Instituut 16
Heilig-Hartlaan 16, 3980  Tessenderlo
T 013 67 02 76 - GSM 0496 17 43 18
www.thhi-tessenderlo.be
Evaluatie: SZAPP <https://szapp-c42bb.firebaseapp.com>
Mindmaps duaal: DLC
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b>, DEMT
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b> en 7DCPT
<https://mind42.com/public/efa9102d-1e45-43e0-b510-41cdaef3c198>




Op wo 20 feb. 2019 om 10:21 schreef Roeland Verbakel <
notifications@github.com>:

**Comment by handihow** [comment]
Ook op de pagina voor leerlingen bij nieuwe evaluatie is nu de link te zien, met link tekst (indien beschikbaar) en anders de volledige link. Deze link staat nu in plaats van de knop "Meer informatie" die nu niet meer beschikbaar is.
