### ISSUE TITLE
Beoordeling

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#12]
Indien een lln een zelfevaluatie heeft gedaan en dit komt bij de leerkracht binnen en de leerkracht doet vervolgens een beoordeling van deze criteria via Snelle invoer dan verdwijnt de zelfevaluatie in de lijst bij beoordeling niet.

**Comment by handihow** [comment]
Dit is een bug. Het probleem was dat de evaluatie status niet werd geupdate naar "Beoordeeld" in dit geval. Dit is nu verholpen.

**Comment by handihow** [comment]
Deze aanpassing is direct doorgezet naar production
