### ISSUE TITLE
rapport downloaden

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#13]
Het downloaden van van het rapport van de lesgroep 7(D)CPT wil niet lukken.

**Comment by handihow** [comment]
Ik heb een error gezien in het opslaan van de grafiek. Ik laat deze nu achterwege indien er een foutmelding is. Dit is geen lange-termijn oplossing maar nu kun je wel het rapport downloaden. Ik zie dat bij de laatste twee leerlingen de grafiek niet is weergegeven op het rapport.
[7(D)CPT_11-3-2019 gecomprimeerd.pdf](https://github.com/handihow/szapp/files/2951424/7.D.CPT_11-3-2019.gecomprimeerd.pdf)


Ook zie ik dat de leerplannen niet altijd zichtbaar zijn op de grafiek. De naam van het leerplan is niet altijd zichtbaar als er teveel kleurenbalken op de grafiek staan.

**Comment by handihow** [comment]
Ik heb deze update doorgevoerd op production, aub het scherm verversen en opnieuw proberen

**Comment by handihow** [comment]
Ik heb verdere verbeteringen doorgevoerd:

Bij labels op de x-as heb ik de instellingen gewijzigd. Zodoende worden de labels nu nooit overgeslagen. Ook worden bij lange namen van het leerplan, deze nu op meerdere regels weergegeven zodat ze goed leesbaar blijven.

Ik heb ook op het rapport alleen de eerste geselecteerde klas weergegeven. Anders liep de tweede geselecteerde klas soms door de volgende regel heen.

Ook snap ik nu waarom de grafiek bij de laatste twee leerlingen niet werd weergegeven, en heb ik dit gecorrigeerd. Het probleem kwam doordat ik de grafiek slechts liet zien op het moment dat de voortgang minder dan 100% was. 
De berekening van de voortgang was echter op basis van 100 / aantal leerlingen, afgerond. In dit geval waren het 22 leerlingen, dus bij iedere stap 4,54 = 5 % erbij. Dus na 20 leerlingen was de progressie 100% en werden de laatste 2 leerlingen niet weergegeven.

Nu rond ik bij de berekening altijd naar beneden (Math.floor functie) en dus gaat dit niet meer fout.

Alle verbeteringen zijn nu doorgevoerd op production. Hopelijk kunnen alle rapporten nu correct worden gedownload.
