### ISSUE TITLE
zichtbaar maken naar wie de leerling de zelfevaluatie verstuurt

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#15]
We hebben nu wel wat zelfevaluaties van leerlingen en we kunnen momenteel niet zien naar wie de leerling zijn zelfevaluatie verstuurt heeft. Het zou handig zijn dat we dit wel kunnen zien zodat we kunnen achterhalen wie van de evaluatoren (leerkrachten) deze evaluatie nog moet doen.
Dit is momenteel het meest dringende.

**Comment by handihow** [comment]
Bij niet beoordeelde evaluaties is nu de naam van de leraar bijgevoegd op de kaart, alsmede een icoontje dat aangeeft dat de beoordeling nog niet compleet is. Er staat bij "Nog niet beoordeeld".

**Comment by LucLens** [comment]
Welke kaart bedoel je?

Op ma 1 apr. 2019 15:05 schreef Roeland Verbakel <notifications@github.com>:

**Comment by handihow** [comment]
De "kaart" is zichtbaar als je via Evaluaties --> kies student --> kies project en dan naar een niet-beoordeelde evaluatie gaat. Deze staat ook aan de linkerkant als je een zelfevaluatie beoordeeld.

**Comment by handihow** [comment]
Kijk aub of dit de bedoeling is, of je iets anders bedoelde, ik heropen dit issue

**Comment by handihow** [comment]
Het uploaden van het plaatje is niet goed gegaan. Ik zie alleen [image: image.png].

**Comment by LucLens** [comment]
Dag Roeland

Ik heb het plaatje nu in bijlage staan.

Met vriendelijke groet,

Luc Lens
Coördinator vakgroepondersteuning techniek, ESF medewerker en coördinator
duaal leren.
Technisch Heilig-Hart Instituut 16
Heilig-Hartlaan 16, 3980  Tessenderlo
T 013 67 02 76 - GSM 0496 17 43 18
www.thhi-tessenderlo.be
Evaluatie: SZAPP <https://szapp-c42bb.firebaseapp.com>
Mindmaps duaal: DLC
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b>, DEMT
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b> en 7DCPT
<https://mind42.com/public/efa9102d-1e45-43e0-b510-41cdaef3c198>




Op di 2 apr. 2019 om 08:10 schreef Roeland Verbakel <
notifications@github.com>:

**Comment by handihow** [comment]
geen bijlage gevonden.. kun je het misschien emailen?

**Comment by handihow** [comment]
De docent is nu te zien bij openklappen van de evaluatie bij niet beoordeelde evaluaties.

**Comment by handihow** [comment]
ook te zien als je daarna op "bekijken" drukt

**Comment by LucLens** [comment]
Dag Roeland

Kan het zijn dat deze functie verdwenen is?

Met vriendelijke groet,

Luc Lens
Coördinator vakgroepondersteuning techniek, ESF medewerker en coördinator
duaal leren.
Technisch Heilig-Hart Instituut 16
Heilig-Hartlaan 16, 3980  Tessenderlo
T 013 67 02 76 - GSM 0496 17 43 18
www.thhi-tessenderlo.be
Evaluatie: SZAPP <https://szapp-c42bb.firebaseapp.com>
Mindmaps duaal: DLC
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b>, DEMT
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b> en 7DCPT
<https://mind42.com/public/efa9102d-1e45-43e0-b510-41cdaef3c198>




Op di 2 apr. 2019 om 10:06 schreef Roeland Verbakel <
notifications@github.com>:

**Comment by handihow** [comment]
Ik zie het nog steeds verschijnen, ook op de production app:

<img width="1440" alt="Schermafbeelding 2019-04-02 om 22 56 52" src="https://user-images.githubusercontent.com/46277832/55435722-c03c1b80-559a-11e9-9547-360bb35c2986.png">

Ook als ik klik op bekijken:

<img width="489" alt="Schermafbeelding 2019-04-02 om 22 57 04" src="https://user-images.githubusercontent.com/46277832/55435732-c631fc80-559a-11e9-8cce-423c1d344213.png">

Let er wel op dat dit alleen verschijnt als de evaluatie nog niet beoordeeld is. 

Ook is het veld niet zichtbaar op mobiel en wellicht ook kleinere tablets (breakpoint 960 px breed).
