### ISSUE TITLE
Kleurenbalken

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#16]
De kleurenbalken geven een verkeerd procentueel getal weer wanneer je met je cursor erover beweegt wat betreft de nog niet beoordeelde competenties (grijs). De overige kleuren worden procentueel wel goed aangegeven.

**Comment by handihow** [comment]
De kleurenbalk is nu gecorrigeerd, grijs zou nu ook het juiste percentage aan moeten geven.
