### ISSUE TITLE
Cedric Coomans

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#17]
Van leerling Cedric Coomans 4IW krijg ik geen grafiek te zien. SZAPP lijkt te blijven zoeken maar er komt niets.
In Firebase zie ik ook niet wat er verkeerd zou kunnen zijn. Wil je dit eens bekijken?

**Comment by handihow** [comment]
Voor zover ik kan zien heeft Cedric Coomans geen enkele evaluatie gedaan.

Daarom wordt er ook geen grafiek gegenereerd.

Zodra hij een beoordeelde evaluatie heeft, zal de grafiek wel verschijnen.
