### ISSUE TITLE
data

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#18]
Na het paasverlof ga ik met leerlingen op Erasmus naar Londen Tableau. Dit is een softwarebedrijf dat dataverwerking doet.
Graag zou ik met hun software onze data van SZAPP eens onderzoeken. Kun je mij tonen hoe ik uit firebase of .. data kan halen waarvan ik dan een soort dashboard kan maken?
Bv. deze data in de vorm van een spreadsheet

**Comment by handihow** [comment]
Hoi Luc,

Ik ben hier een tijdje mee bezig geweest. Eerst leek het makkelijk maar is het niet zo.. helaas.

Ik heb eerst de standaard oplossing bekeken van Google Cloud Firestore in dit [artikel](https://firebase.google.com/docs/firestore/manage-data/export-import). Daar bleek geen oplossing te staan voor csv export. 

Verder gezocht naar oplossingen. Er is een mogelijkheid om via Cloud Functions een csv bestand te schrijven naar de Storage. Echter, hiervoor is een functie nodig die ook aangestuurd moet worden. Als je dit via HTTP doet dan wordt dit potentieel onveilig (iedereen met de link kan dan alle gegevens downloaden). Het csv bestand moet dus niet direct te downloaden zijn, maar eerst naar Firebase Storage worden geschreven waar hij dan kan worden gedownload. 

Dit vereist dan weer een Functie, met bijbehorende Pub/Sub commando. Dit is allemaal mogelijk maar voor een eenmalige download van de gegevens is dit veel werk.

Daarna ben ik weer terug gegaan naar het artikel. Hierin stond wel dat de gegevens kunnen worden binnengehaald in Big Query. Dat heb ik daarna ook gedaan, en na weer wat geklooi is het me uiteindelijk gelukt om een JSON bestand van alle evaluaties in mijn Google drive te zetten. Dit bestand heb ik met jou gedeeld.

Hopelijk weet dit bedrijf er raad mee. Anders kun je ook nog naar de Big Query omgeving op het SZAPP project, daar staat de tabel reeds ingeladen. Wellicht kunnen de mensen in Londen daar ook mee overweg. Veel reisplezier.
