### ISSUE TITLE
klasnummer

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#19]
Is het mogelijk dat in het "Profiel" de leerling ook zijn klasnummer in kan geven. In SZAPP zouden dan alle leerlingenlijsten gesorteerd worden op klasnummer i.p.v. op voornaam.

**Comment by handihow** [comment]
Beste Luc,

Zeker mogelijk, en ik ben bezig met de implementatie. De vragen die ik hierbij heb:

1. Er is nu een lijst met klassen en de leerling kan 1 of meerdere klassen kiezen in zijn profiel
- hoe relateert het klasnummer zich met deze lijst klassen?

2. Is het klasnummer een nummer veld of een tekst veld? Een nummerveld kan alleen gehele getallen bevatten

3. Hoe kan deze verandering worden doorgevoerd? Gaan jullie alle leerlingen benaderen om het profiel te updaten? Ik heb gemerkt dat als ik automatisch wil sorteren, de leerlingen zonder dit veld op hun profiel niet in de lijst verschijnen, dus dat kan voor problemen zorgen. Of moet het veld eerst bij iedere leerling worden ingevuld, zo ja, met welke waarde?

4. Is het later de bedoeling dat dit veld via een koppeling automatisch wordt gevuld (vanuit een leerlingvolgsysteem)?

**Comment by LucLens** [comment]
1. Leerling zou in zijn profiel maar 1 klas mogen kunnen aanduiden. Natuurlijk als hij/zij naar het volgende jaar gaat moet hij/zij zijn/haar klas kunnen wijzigen. In één klas is elk klasnummer uniek.
2. klasnummer is een nummer veld
3. Best dat je elke leerling op voorhand het klasnummer 99 geeft. Leerlingen kunnen dan nadien hun klasnummer in profiel wijzigen.
4. Hopelijk wel. Voorlopig nog niet.

**Comment by handihow** [comment]
Dank voor je antwoord.

Als ik het goed begrijp, is het klasnummer dan het leerjaar?

Je krijgt dus bijvoorbeeld de klassen 1a, 1b, 1c en de leerling kan hier
uit selecteren (maar niet meerdere zoals nu), en het klasnummer is dan 1?

Ik bedoel niet automatisch maar dit is dan wat de leerling invult bij
klasnummer.



Op do 6 jun. 2019 13:45 schreef LucLens <notifications@github.com>:

**Comment by LucLens** [comment]
In België is een klasnummer gebasseerd op de familienaam. Bv.
Lens Luc klasnummer 1
Thijs Richard klasnummer 2
Verbakel Roeland klasnummer 3

**Comment by handihow** [comment]
Luc, dit is nu geimplementeerd op de staging app. Klasnummers zijn gezet op 99, en kunnen worden aangepast in het profiel. Sortering is op klasnummer en daarna naam. Leerlingen kunnen voortaan nog maar 1 klas selecteren (leraren nog steeds meerdere).

Als dit in orde is, dan aub groen licht geven, dan kan ik dit doorvoeren op production.

**Comment by LucLens** [comment]
Doe maar.
Merci

**Comment by handihow** [comment]
Doorgevoerd op production
