### ISSUE TITLE
drop down menu

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#2]
BEOORDELING

Op GSM zie je maar 6 lijntjes in "Selecteer competentie". Je kunt niet scrollen naar de andere competenties.

**Comment by handihow** [comment]
- Alle select inputs zijn verplaatst naar een eigen component in "shared" folder zodat ze in verschillende onderdelen van de app kunnen worden hergebruikt. Dit omdat iedere select input nu een vrij complex en lang stuk code werd. 

- Er wordt gekeken of de gebruiker op mobiel is, in dat geval wordt de native select geactiveerd. Deze native select is op mobiel goed ondersteund.

- Bij het selecteren van een leerling was er gebruik gemaakt van een "mat-autocomplete". Hiervoor is geen support op mobiel. Daarom is er voor mobiel een andere oplossing. Men kiest dan eerst de klas uit een lijst, en vervolgens de leerling uit een lijst. Dit is 1 stapje extra maar anders kon ik het niet werkend krijgen op mobiel.

Deze aanpassingen zijn nu beschikbaar op de staging app.
