### ISSUE TITLE
gegevenstoegang

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#20]
Je hebt mij al eens een excell-lijst bezorgd met alle gegevens uit firebase van SZAPP. Kan dit automatisch bv. wekelijks gebeuren?

**Comment by handihow** [comment]
Luc, ik heb nu een download-optie gecreëerd. Dit kun je vinden bij Beheer --> Downloads
Je kunt records downloaden. 
Ik heb momenteel alleen jou en Richard hiervoor geautoriseerd. Mochten er meer mensen gebruik van willen maken, laat me dan aub het email adres van betreffende personen weten.

Het verzoek tot gegevens wordt geautoriseerd via een Custom Claim op jullie profiel. Alle andere gebruikers hebben deze claims niet. Zelfs als ze wel toegang hebben tot de pagina, zullen ze een foutmelding krijgen als ze proberen te downloaden.

**Comment by LucLens** [comment]
Dag Roeland

In SZAPP kan ik dit niet terugvinden?

Met vriendelijke groet,

Luc Lens
Coördinator vakgroepondersteuning techniek, ESF medewerker en coördinator
duaal leren.
Technisch Heilig-Hart Instituut 16
Heilig-Hartlaan 16, 3980  Tessenderlo
T 013 67 02 76 - GSM 0496 17 43 18
www.thhi-tessenderlo.be
Evaluatie: SZAPP <https://szapp-c42bb.firebaseapp.com>
Mindmaps duaal: DLC
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b>, DEMT
<https://mind42.com/public/1d499e90-aafc-44de-b82a-f7890ae6e88b> en 7DCPT
<https://mind42.com/public/efa9102d-1e45-43e0-b510-41cdaef3c198>




Op di 4 jun. 2019 om 20:34 schreef Roeland Verbakel <
notifications@github.com>:

**Comment by handihow** [comment]
Hoi Luc

Als het goed is, alleen in production en bij Beheer -> Downloads

Groeten

Roeland

Op wo 5 jun. 2019 09:09 schreef LucLens <notifications@github.com>:

**Comment by LucLens** [comment]
Gevonden!
Is inderdaad handig. Alleen zou het handiger zijn mocht je niet het aantal evaluaties kunnen downloaden maar wel de periode op basis van datum.

**Comment by handihow** [comment]
Dit is een idee dat ik wellicht in latere versies kan verwerken. Hou rekening mee dat deze functie niet op grote schaal moet worden gebruikt door iedereen, want dit kan leiden tot zeer veel database reads en daarom hoge kosten van Firebase. Vandaar ook dat ik in eerste instantie iedereen bewust wil laten zijn van de hoeveelheid gegevens die wordt opgevraagd, en hier een redelijke limiet aan te stellen mbv de schuif. Ook zou ik voorstellen dat deze functionaliteit niet voor veel mensen beschikbaar is. Buiten de app zijn de gegevens ook niet meer beveiligd.
