### ISSUE TITLE
Geschiedenis beoordeelde evaluaties

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#21]
Indien je de geschiedenis van beoordeelde evaluaties opent, krijg je een ongeordende lijst. Deze zou zeker volgens datum moeten gesorteerd worden. Anders kan het zijn dat niet de laatst ingegeven beoordeling de leerling te zien krijgt maar een vroeger ingegeven beoordeling.

**Comment by handihow** [comment]
Dit wordt meegenomen in de komende update

**Comment by handihow** [comment]
Is nu al beschikbaar op staging app

**Comment by LucLens** [comment]
Mag je zeker al naar production zetten.
Bedankt.

**Comment by handihow** [comment]
ik zal dit vanavond laat doen, als er (bijna) niemand met het systeem werkt

**Comment by handihow** [comment]
Doorgevoerd op production
