### ISSUE TITLE
evaluatie van competentie in project verdwijnt

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#23]
Probleem:

Een competentie komt in 2 projecten voor.
Indien deze competentie in een bedrijf geëvalueerd  is en dezelfde competentie wordt daarna op school in een ander project geëvalueerd, verdwijnt de volledige evaluatie in het project van het bedrijf. In het algemeen overzicht blijft alles wel staan.

vb.
Volgende competentie:

Standaardtraject 7DCPT - 267.01 - kent de functie van terugslagkleppen; drukreductieventielen en drukbeveiligingskleppen; kan de werking van vacuümbrekers en breekplaten toelichten
> Terugslagkleppen; drukreductie én drukbeveiliging

Komt in volgende 2 projecten voor:

BEDRIJF - 7(D)CPT - Toegepaste Mechanica
2019 BEDR 7DCP 2001

Kleppen en kranen
2019-THHI-7CPT-1005

Je zult nu zien dat deze competentie in project "Kleppen en kranen 2019-THHI-7CPT-1005" wel kleuren bevat en in project "BEDRIJF - 7(D)CPT - Toegepaste Mechanica 2019 BEDR 7DCP 2001" staat niets meer.

**Comment by handihow** [comment]
De vorige beoordeling is waarschijnlijk niet geheel verdwenen maar staat nog in de geschiedenis van de evaluaties. Echter, de grafiek van het project wordt gemaakt op basis van de meest actuele beoordeling, en er wordt niet gezocht in de geschiedenis van beoordelingen. 

Het is technisch mogelijk om de grafiek te genereren (deels) op basis van de beoordelingen in de geschiedenis maar op dit moment is deze functionaliteit niet aanwezig.

**Comment by LucLens** [comment]
Ik denk dat je mij niet goed begrijpt.
Volgende zie ik in Overzicht Leerplan van leerling Lucas Dierckx staan, wat dus goed is:

![competentie in Overzicht Leerplan](https://user-images.githubusercontent.com/46919090/59603328-711d7580-9109-11e9-8579-70dbdb366161.png)


In project "Kleppen en kranen 2019-THHI-7CPT-1005" zie ik bij Lucas het volgende, wat dus ook goed is. Hierin is trouwens de laatste evaluatie door de school ingezet:

![competentie in project 2019 THHI 7CPT 1005 Kleppen en kranen_](https://user-images.githubusercontent.com/46919090/59603403-a32ed780-9109-11e9-8f0a-8ae184707867.png)


In project "BEDRIJF - 7(D)CPT - Toegepaste Mechanica 2019 BEDR 7DCP 2001" zie ik echter volgende, waar dus geen enkele evaluatie instaat:

![competentie in project BEDRIJF - 7(D)CPT - Toegepaste Mechanica 2019 BEDR 7DCP 2001](https://user-images.githubusercontent.com/46919090/59603525-ebe69080-9109-11e9-8dc7-ed2b39cb095d.png)

**Comment by handihow** [comment]
Luc, 
Ik begrijp het probleem, het is gerelateerd aan de manier waarop de evaluaties van de leerling worden gefilterd voor dit overzicht. Dit gebeurd momenteel op project-basis. Omdat de evaluatie daarna reeds is gedaan in een ander project, komt deze niet te voorschijn in het overzicht van het andere project. 

De oplossing ligt in het wijzigen van de query voor evaluaties in dit overzicht, hieraan wordt gewerkt.

**Comment by handihow** [comment]
Luc, dit probleem is nu verholpen op de staging app, doordat de evaluatie nu wordt opgehaald aan de hand van het competentienummer en leerling identificatie nummer ipv op basis van het project.

Je kunt dit nu uittesten.

**Comment by LucLens** [comment]
Werkt prima.
Mag ook al naar production zetten.
Bedankt.

Op vr 21 jun. 2019 12:06 schreef Roeland Verbakel <notifications@github.com

**Comment by handihow** [comment]
is nu beschikbaar op production
