### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#6]
Is het mogelijk dat bij de Filter de laatst ingegeven filter onthouden blijft?
Bv. als je nu bij Projecten in de Filter 7DCPT vermeld en klikt een project aan en gaat er terug uit, moet je terug 7DCPT intypen naast Filter om je vorige lijst te krijgen. Komt geregeld voor.

**Comment by handihow** [comment]
Filters bij leerplannen, projecten en lesgroepen worden nu bewaard.
Ik zal voortaan het issue open laten totdat jij het afvinkt als OK nadat je het hebt uitgetest.
