### ISSUE TITLE
snel evalueren

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#7]
BEOORDELING

Bij snel evalueren van lesgroepen is er de vraag om de ingave van Project te behouden nadat je als leraar op Bewaar hebt geklikt. Indien mogelijk natuurlijk.

**Comment by handihow** [comment]
Dit is nu aangepast. Het project en de competentie blijven geselecteerd, de rest van het formulier wordt gereset. Compententie kan dan opnieuw worden beoordeeld, of er kan een andere worden geselecteerd.
