### ISSUE TITLE
foto mee doorsturen

### ISSUE THREAD

**Issue by LucLens** [handihow/szapp#9]
Indien een leerling een zelfevaluatie met foto doorstuurt en de evaluator opent deze evaluatie, dan komt de foto niet te voorschijn. Er blijft dan een cirkel draaien.
Ook zou het beter zijn dat  bij het maken van een foto de leerling pas op Bewaren kan klikken nadat de foto 100% is ingeladen. Anders wordt er geen foto mee doorgestuurd en de leerling krijgt hiervan ook geen mededeling.

**Comment by handihow** [comment]
Problemen met de foto's zijn nu opgelost. Ook wordt de knop "Bewaren" pas weer actief als de foto compleet is geupload. 

Het probleem met de ronddraaiende cirkel is dat op de achtergrond, de grote foto ook wordt geconverteerd naar een kleiner formaat. Dit kleinere formaat wordt getoond op de evaluatie. Echter, de functie die de conversie doet, gaf een foutmelding en werkte dus niet. Dit kwam door wijzigingen in de import syntax, waardoor de "Storage bucket" niet meer beschikbaar was.

Daardoor bleef de component in de "loading" status (ronddraaiende cirkel) omdat het plaatje dus niet werd gevonden. Het origineel zou nog steeds beschikbaar moeten zijn door op "Inzoomen" te klikken. 

De functie is nu hersteld en werkt weer, zodat ook het kleinere plaatje nu weer wordt gegenereerd.

Ook is het formulier aangepast zodat zodra je op "upload image" klikt, de "Bewaar" knop gedeactiveerd wordt.

**Comment by handihow** [comment]
Aanpassingen zijn doorgevoerd op Staging, en zo spoedig mogelijk ook op Production.

**Comment by handihow** [comment]
De aanpassingen zijn nu ook op Production doorgevoerd
